### ISSUE TITLE
I meet a multiple definition of error when use gohs

### ISSUE THREAD

**Issue by xvsfekcn** [flier/gohs#13]
go version 1.11.4
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work"
GOPROXY=""
GORACE=""
GOROOT="/root/go"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="/usr/local/gcc-5.3.0/bin/gcc"
CXX="/usr/local/gcc-5.3.0/bin/g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build725949828=/tmp/go-build -gno-record-gcc-switches"
============================
ERROR INFO
/root/go/pkg/tool/linux_amd64/link: running /usr/local/gcc-5.3.0/bin/gcc failed: exit status 1
/lib/../lib64/libpthread.a(libpthread.o): In function `__libc_sigaction':
(.text+0x8590): multiple definition of `__libc_sigaction'
/lib/../lib64/libc.a(sigaction.o):(.text+0x20): first defined here
/lib/../lib64/libpthread.a(libpthread.o): In function `__connect_nocancel':
(.text+0x7969): multiple definition of `__connect_nocancel'
/lib/../lib64/libc.a(connect.o):(.text+0x9): first defined here
/lib/../lib64/libpthread.a(libpthread.o): In function `__libc_fcntl':
(.text+0x77e0): multiple definition of `__libc_fcntl'
/lib/../lib64/libc.a(fcntl.o):(.text+0xa0): first defined here
/lib/../lib64/libpthread.a(libpthread.o): In function `_IO_funlockfile':
(.text+0x8530): multiple definition of `_IO_funlockfile'
/lib/../lib64/libc.a(funlockfile.o):(.text+0x0): first defined here
/lib/../lib64/libpthread.a(libpthread.o): In function `__libc_nanosleep':
(.text+0x7dc0): multiple definition of `__libc_nanosleep'
/lib/../lib64/libc.a(nanosleep.o):(.text+0x0): first defined here
/lib/../lib64/libpthread.a(libpthread.o): In function `__read':
(.text+0x7680): multiple definition of `__libc_read'
/lib/../lib64/libc.a(read.o):(.text+0x0): first defined here
/lib/../lib64/libpthread.a(libpthread.o): In function `__open_nocancel':
(.text+0x7e29): multiple definition of `__open_nocancel'
/lib/../lib64/libc.a(open.o):(.text+0x9): first defined here
/lib/../lib64/libpthread.a(libpthread.o): In function `__lseek_nocancel':
(.text+0x7d09): multiple definition of `__lseek_nocancel'
/lib/../lib64/libc.a(llseek.o):(.text+0x9): first defined here
/lib/../lib64/libpthread.a(libpthread.o): In function `__read_nocancel':
(.text+0x7689): multiple definition of `__read_nocancel'
/lib/../lib64/libc.a(read.o):(.text+0x9): first defined here
/lib/../lib64/libpthread.a(libpthread.o): In function `send':
=================================================
I used hyperscan in my program with two different package. And if i only use hyperscan in one package and everything is ok.

**Comment by flier** [comment]
I'm not sure, but it seems you try to link libc and libpthread with static library?

Can you try to link those library with .so ?
```
$ ldd simplegrep
	linux-vdso.so.1 (0x00007fff78d88000)
	libhs.so.4 => /usr/lib/x86_64-linux-gnu/libhs.so.4 (0x00007f98b75b1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f98b7392000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f98b6fa1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f98b6c18000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f98b687a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f98b6662000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f98b80b6000)
```
