### ISSUE TITLE
Could not match empty buffer even on `HS_FLAG_ALLOWEMPTY` enforced

### ISSUE THREAD

**Issue by slayercat** [flier/gohs#16]
Hyperscan allows `HS_FLAG_ALLOWEMPTY`. As the doc says: 
(see https://intel.github.io/hyperscan/dev-reference/api_files.html)

```
HS_FLAG_ALLOWEMPTY
Compile flag: Allow expressions that can match against empty buffers.

This flag instructs the compiler to allow expressions that can match against empty buffers, such as .?, .*, (a|). Since Hyperscan can return every possible match for an expression, such expressions generally execute very slowly; the default behaviour is to return an error when an attempt to compile one is made. Using this flag will force the compiler to allow such an expression.
```

In `hyperscan` [test](https://github.com/intel/hyperscan/blob/7dfaca66355e53de5c4f38602420b13a6af45206/unit/hyperscan/behaviour.cpp#L1117)  shows hyperscan supports this behavior.

But because of this [code](https://github.com/flier/gohs/blob/417cefa5e1c7e223634edf8ab62deba2db4e5964/hyperscan/internal.go#L919):
```golang

func hsScan(db hsDatabase, data []byte, flags ScanFlag, scratch hsScratch, onEvent hsMatchEventHandler, context interface{}) error {
	if len(data) == 0 {
		return HsError(C.HS_INVALID)
	}
```

the flag will not work in the `gohs` project.

**Comment by flier** [comment]
Thanks @slayercat, the issue should be solved.
