### ISSUE TITLE
Get regexp index from match

### ISSUE THREAD

**Issue by rashkur** [flier/gohs#18]
Hello there. Thank you for nice library. I'm playing with your examples now, but cannot find, how to get index of matched regex from database. For my use case it would be perfect (I'm uploading huge table of regular expressions into block databse and want to get only matched regexp index to return url by index from second table).

**Comment by flier** [comment]
Please use [DatabaseBuilder](https://godoc.org/github.com/flier/gohs/hyperscan#DatabaseBuilder) to build database if you want to match multi-patterns, and the event will give you the matched pattern id.
