### ISSUE TITLE
How to use it by right method?

### ISSUE THREAD

**Issue by FelixSeptem** [flier/gohs#23]
My demand is to match one string to multi regex. And I write code below, I get a `Database` and what shall I do next?I don't find right method to call in `Database` or I missed something?
```go
package main

import "github.com/flier/gohs/hyperscan"

func main(){
    regs := []hyperscan.Expression{
        hyperscan.Expression("..."),
        hyperscan.Expression("..."),
    }
    db := new(hyperscan.DatabaseBuilder)
    db.AddExpressions(regs...).Build()
    // what shall I do next? is there some method like db.Match("target string") or something?
}
```

**Comment by flier** [comment]
It depends on how you want to use it, for example, you can specify the generate `BlockDatabase` with `BlockMode` ([ModeFlag](https://pkg.go.dev/github.com/flier/gohs/hyperscan?tab=doc#ModeFlag)).

Please check the [unit test](https://github.com/flier/gohs/blob/master/hyperscan/compile_test.go#L92) for more detail.

**Comment by FelixSeptem** [comment]
> It depends on how you want to use it, for example, you can specify the generate `BlockDatabase` with `BlockMode` ([ModeFlag](https://pkg.go.dev/github.com/flier/gohs/hyperscan?tab=doc#ModeFlag)).
> 
> Please check the [unit test](https://github.com/flier/gohs/blob/master/hyperscan/compile_test.go#L92) for more detail.

not really help for me, my question is not found the right method to call in struct [Database](https://pkg.go.dev/github.com/flier/gohs/hyperscan?tab=doc#Database), which is generated by `DatabaseBuilder.Build()`
