### ISSUE TITLE
Scratch space and gorutines

### ISSUE THREAD

**Issue by jmdacruz** [flier/gohs#29]
Quick question about scratch space and gorutines: According to the hyperscan documentation (https://intel.github.io/hyperscan/dev-reference/runtime.html#scratch-space), a scratch space should be cloned if it is going to be used by multiple threads. How does this map to gorutines? Is there a way to ensure that the binding clones the scratch space for each underlying thread? The only alternative I see is that the caller creates a channel with a fixed size of the scratch clones, and gorutines use the channel to synchronize

**Comment by flier** [comment]
I think any sync method will work, e.g. `sync.Pool`, if you make sure the `Scratch` only be used by one goroutine.

**Comment by jmdacruz** [comment]
We tried `sync.Pool`, but channels seem to work better for our hyperscan use case, given the thread locking due to the CGO calls. Since we know only N (N being the number of threads) gorutines will be able to make calls to hyperscan at a time, we can then pre-provision a channel with M (M > N) instances of the scratch space and have gorutines pull from there before making the call to hyperscan (and send back to the channel once finished). The advantages over `sync.Pool` seem to be: 1) more latency predictability, since we pre-allocate only once at the beginning, and 2) potentially less garbage collection churn (given that `sync.Pool` may remove items from the pool at any time)

Thoughts on this approach?

**Comment by flier** [comment]
Of course, if you have a clear expectation of the number of `Scratch` you will need, `sync.Pool` is not necessary at all. For this scenario, you can try using a lock-free `Slab` data structure.
