### ISSUE TITLE
Failed to build with Go 1.8

### ISSUE THREAD

**Issue by starius** [flier/gohs#4]
Go 1.8:
```
gopath/src/github.com/flier/gohs/hyperscan/internal.go:904: cannot use unsafe.Pointer(db)
 (type unsafe.Pointer) as type *C.struct_hs_database in argument to func literal
```
Go 1.7.4 works well.

This issue can be related to this part of [the release notes](https://golang.org/doc/go1.8#cmd_cgo
):
> If cgo is used to call a C function passing a pointer to a C union, and if the C union can contain any pointer values, and if cgo pointer checking is enabled (as it is by default), the union value is now checked for Go pointers.

I am crosscompiling from Linux to Windows.

**Comment by starius** [comment]
Removing `unsafe.Pointer` from that line fixes the build. Why was it added there?

**Comment by flier** [comment]
In fact, I don't remember, seems fix some compatibility issue for old time's.

The cgo changed more strict from 1.7, we have to make golang happy anyhow :)

Patch merged, Thanks very much!
