### ISSUE TITLE
How to use gohs on Windows（use Goland to development）?

### ISSUE THREAD

**Issue by iFANGXIE** [flier/gohs#45]
I tried to compile Hyperscan with Visual Studio 2022 based on the docs and successfully ran bin/unit-hyperscan. The test passed, but GOHS still doesn't seem to be able to find the relevant file, and I tried to search globally and didn't find the file mentioned in the error.

The error is as follows：
\# pkg-config --cflags  -- libhs
Package libhs was not found in the pkg-config search path.
Perhaps you should add the directory containing `libhs.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libhs', required by 'virtual:world', not found
pkg-config: exit status 1

**Comment by Nyx2022** [comment]
hello，HFANFA ，do you have solved this problem,if so ,can you share your libhs.pc for us,thank you
