### ISSUE TITLE
cgo preprocessing failed with Hyperscan library on Linux amd64

### ISSUE THREAD

**Issue by ghoze** [flier/gohs#52]
I'm encountering a build error with the github.com/flier/gohs package on Linux amd64 when using Go with cgo and the Hyperscan library. Despite properly configuring the PKG_CONFIG_PATH, CGO_CFLAGS, and CGO_LDFLAGS environment variables, I'm still getting a cgo preprocessing error during compilation.

Error message:
```go
/go/pkg/mod/github.com/flier/gohs@v1.2.1/internal/hs/allocator.go:42:8: could not import C (cgo preprocessing failed) (compile)
```

Steps to reproduce:
1. Install the Hyperscan library and its development package.
2. Set the PKG_CONFIG_PATH, CGO_CFLAGS, and CGO_LDFLAGS environment variables based on the installed Hyperscan library.
3. Run rake lint on a project that depends on the github.com/flier/gohs package.

Environment:
- OS: Ubuntu 18.04
- Go version: go version go1.19.6 linux/amd64
- Hyperscan version: 4.7.0

Troubleshooting steps taken:
1. Verified the installation of Hyperscan and its development package.
2. Checked the paths to header and library files using pkg-config.
3. Set the CGO_CFLAGS and CGO_LDFLAGS environment variables based on pkg-config output.
4. Cleaned the Go cache using go clean -modcache.

Despite following these steps, the issue persists. Any help or guidance would be greatly appreciated.

**Comment by flier** [comment]
It seem you haven't CGO support, you may try `apt install build-essential` first.

**Comment by ghoze** [comment]
Actually the problem was much deeper than this.
It had to do with the default HyperScan version installed on the container. The default HyperScan version was 4.7 and the go lib defaults to v5, eventually I switched to a different distribution where HyperScan v5 is the default one and it worked.
