### ISSUE TITLE
no docs for chimera (https://pkg.go.dev/github.com/flier/gohs/chimera)

### ISSUE THREAD

**Issue by dwisiswant0** [flier/gohs#59]

**Comment by dvershinin** [comment]
Docs are really required, especially concerning lack of `.SomLeftMost` analogue from hyperscan. Is there a way to use it with Chimera?

**Comment by flier** [comment]
A build tag `//go:build chimera` is used to ensure that chimera package are only compiled if the chimera library are provided.

But `pkg.go.dev` only supports a few of [build context](https://pkg.go.dev/about#build-context), and no custom build tag are provided.

So, any source code with build tag will not be included in `godoc` and `pkg.go.dev` golang/go#3398

To solve this problem, I needed to find a way to separate the `hyperscan` and `chimera` packages, avoiding the use of build tag, but possibly affecting the existing API
