### ISSUE TITLE
there is no way to reset m.handler

### ISSUE THREAD

**Issue by taowen** [flier/gohs#7]
```go
func (m *blockMatcher) scan(data []byte) error {
	if err := m.scanner.Scan(data, m.scratch, m.handler.Handle, nil); err != nil {
		return err
	}

	return nil
}
```

m.handler.matched keeps growing

**Comment by flier** [comment]
Please try the `develop` branch with [auto reset blockMatcher.handler](https://github.com/flier/gohs/commit/677db64e157dbd9ba239d8b8948b171070b8a8e1)

**Comment by flier** [comment]
merged to `master` branch
