### ISSUE TITLE
Package libhs was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by 5up3rc** [flier/gohs#9]
# pkg-config --cflags libhs --static
Package libhs was not found in the pkg-config search path.
Perhaps you should add the directory containing `libhs.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libhs' found
pkg-config: exit status 1

**Comment by mbulatova** [comment]
It seems you just need to do
`export PKG_CONFIG_PATH=<path-to-hyperscan-build-dir>`
libhs.pc is located there

**Comment by flier** [comment]
Yes, please ensure your libhs.pc in the PKG_CONFIG_PATH path, check `man pkg-config` for more details.

**Comment by yjfvictor** [comment]
What is "libhs"? Where can I find it? Does it even exist on my computer?

**Comment by flier** [comment]
@yjfvictor hyperscan will generate [libhs.pc](https://github.com/intel/hyperscan/blob/master/libhs.pc.in) and install it to your target directory

**Comment by flier** [comment]
If you want to build hyperscan from source code, please check the document

https://intel.github.io/hyperscan/dev-reference/getting_started.html

or you could use `homebrew install hyperscan` or `apt-get install libhyperscan-dev` which should include it.

**Comment by flier** [comment]
If you want to build hyperscan from source code, please check the document

https://intel.github.io/hyperscan/dev-reference/getting_started.html

or you could use `homebrew install hyperscan` or `apt-get install libhyperscan-dev` which should include it.
